env:
  es6: true
extends:
  - "plugin:@typescript-eslint/recommended"
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  no-unused-vars: off
  indent: off
  semi: off
  "@typescript-eslint/indent": [error, 2]
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
overrides:
  - files:
      - tests/**/*.ts
      - "**/*.spec.ts"
    env:
      mocha: true
    rules:
      "@typescript-eslint/explicit-function-return-type": off
      "@typescript-eslint/no-unused-vars": warn
      require-jsdoc: off
