language: node_js
node_js:
- lts/*
# - node
services:
- mongodb
env:
  global:
    # FIREBASE_TOKEN
    - secure: nU8Rsh/vB839pyaW/RJOxJs7Jt8thZPcdd9Q5h9Z8OXX3k79ogTNLiHEbg/s/sMAbMnmCSm1x+4d+ArAq0nme9IJMI+h2sHGypLmG4DDE5PyX6f7vAYGlB6/wmwcLcv8cwh+Z44pKzIm1CbJhfkcuJllDqwy2UlmyHH2cAy1WX4xcFieYA7xLv5GTUqa9Pvc9EnW9tp0DhSscyxXwLSQMw4AVBuvjO/FEIaVPeUQl+ojJ6fFlyqsDAmI0wcvSso2xJyStqUv2oVe9jkxAGP1zg6AXsCjZf2lKEkmoIZajbz2NKTvbxZaFiG8Q9VE8YoAkXBeQDcEetE+9Mzg1S+vWOix3C0kbei6Zpu1BuG6169Opu1auCMN12d982We/+8uj8Zl1JLm2EiR2D4YsYhgViuGEPMvv97nSVALB+T0m8GP+CuEPV704V2e8afCuf6ZBziSXuhIcwKnqBhOBHbVS8hDqUM5AUVWdSapzg1CK5syElOy62iOexVLR9NnhGaO2ss6MPBLfwZR1quAmz4rb+n9Y6q6A7X+GauDsaesWhCj1pZqQAJDq34EPqmvlDXHVQ0RWerRydLTRBFD1Y4y20SkgukgQWCU1IWM5j47WpRCnZ4QfhYfjYld/GG9B702V0RgXcsLpDVyjJY7k9shDa0m5t9cPrfz17wLmbKkQ7c=
before_install:
- openssl aes-256-cbc -K $encrypted_2b2012393641_key -iv $encrypted_2b2012393641_iv
  -in firebase.json.enc -out tests/config/firebase.json -d
script:
- npm run lint
- nyc npm test
after_success:
- if [ "${TRAVIS_NODE_VERSION}" = "lts/*" ]; then nyc report --reporter=text-lcov |
  coveralls; fi
